#ICA-DICT
METHOD_ICA = "ICA"
METHOD_DICTIONARY_LEARNING = "DICT"

NUM_IMAGES_FOR_COMPONENTS = 10
NUM_COMPONENTS = 8
LOW_PASS = 0.08
HIGH_PASS = 0.01

#SVM
N_SPLITS = 10#15
TEST_SIZE = 25#15

#RNN
SPLIT_SIZE = 0.25
RANDOM_STATE = 8
SAMPLING_RANDOM_STATE = 1 #required between (0,1] when sampling

#
TEMP_TS = 'temp_ts.npy'
TEMP_CL = 'temp_cl.npy'


